# Generated by Django 4.1.2 on 2022-11-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0005_mensaje"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name_plural": "Blogs"},
        ),
        migrations.AddField(
            model_name="blog",
            name="autor_nombre_completo",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="cuerpo",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
